### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#1]
Destkopon:
- felül egy sorban
- sticky

Mobilon:
- csík rajta hamburgerrel és logóval
- hamburger nyomásnál előjön képernyőt befedő drawer, egy oszlopban a menüpontok
- sticky (ha nem nagyon zavaró)

Jelenlegi aloldal linkje átszínezve.
Linkek felé hoverelve is változhat a színe

**Comment by perryd01** [comment]
todo kicserélni a logót svgre

**Comment by NoszDom** [comment]
Délután kiexportálom, és felrakom drivera
