### ISSUE TITLE
Default kép beállítása contentfulban

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#116]

**Comment by perryd01** [comment]
#127 -ben Tagoknál fixelve van, news és event esetén placekitten a default.
Így is fennáll még az issue? @NoszDom

**Comment by perryd01** [comment]
Kódból van fixelve, mivel contentfulban nincs opció default image-re

**Comment by NoszDom** [comment]
Ha jól emlékszem, azért lett felvéve az issue, hogy a placekitten legyen kiírtva. Nem baj, ha nem contentfulból jön, lényeg hogy legyen vmi default kép, ami nem macska, pl ez csak alacsonyabb opacityvel, hogy szürkés legyen:
![image](https://user-images.githubusercontent.com/61868789/155965282-a8a65953-1f04-4277-a569-11fdf9e5bdc8.png)
