### ISSUE TITLE
Tag komponens

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#16]
- email címre kattintva mailto-s megnyitás

**Comment by perryd01** [comment]
mit csinálok, ha hosszabb a név/pozíció/email mint amivel meg lett tervezve? ha simán csak nagyobb a magasság, akkor a "kép a bal oldalra való illesztése dolog" nem fog szépen kinézni
@NoszDom @OmTheTurtle 
![Screenshot_20210925_200501](https://user-images.githubusercontent.com/46491285/134781625-e1f6d4a8-cf58-44ab-b9ad-cef0ea2ca3aa.png)

**Comment by perryd01** [comment]
simán eggyel kisebb betűméret ha x-nél hosszabb a szöveg?

**Comment by OmTheTurtle** [comment]
Szerintem a kisebb betűméret lehet a legjobb megoldás, meg esetleg egy oszlopos nézetben kicsit szélesebb kártyák.

**Comment by OmTheTurtle** [comment]
Illetve lehet elrendezésben nagyobb térköz az egymás alatti szövegeknek, hogyha több sorba törik, akkor is kiférjen az adott magasságon.

**Comment by NoszDom** [comment]
Mindkét fentebbi megoldás valid, ++ tőlem
