### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#2]
- ugyanolyan minden nézeten
- ikonokhoz még nincsenek linkek
- figmához képest plusz elem alul schdesign megjelölés hasonlóan, mint a [g7.sch.bme.hu](g7.sch.bme.hu)-n
- ikonok felé hoverelve átszínezhetjük, pl figmában levő világos türkizre vagy világos rózsaszínre
- email címre kattintva mailto-s megnyitás

**Comment by gergoradeczki** [comment]
mikor lesznek az ikonokhoz linkek? vagy egyáltalán lesznek-e, kellenek-e a social médiás ikonok?

**Comment by NoszDom** [comment]
Ők kérték hogy legyenek ott, szóval lesznek majd

**Comment by perryd01** [comment]
social linkek is contentfulból jönnek?

**Comment by NoszDom** [comment]
Jó, ha azt is tudják változtatni, szóval igen
