### ISSUE TITLE
Hamburger menu fix

### ISSUE THREAD

**Issue by OmTheTurtle** [simonyiszk/mabe#35]
Ha aloldalak között navigálunk a hamburger menün keresztül, akkor nyitva marad a menü, ami egészen zavaró.

**Comment by perryd01** [comment]
@OmTheTurtle elég simán Link kattintásra az `isNavbarOpen` változót flippelni?

**Comment by OmTheTurtle** [comment]
Igen, a next router-rel meg tudod csinálni, hogy a routing esemény hatására bezárod a hamburger menüt, lásd [itt](https://github.com/OmTheTurtle/simonyi-konyvtar/blob/d0ddfb2467a4b7822284ce8e6e727be5c11905fc/src/components/Navbar.tsx#L17)

**Comment by perryd01** [comment]
köszi, fixeltem.
illetve azt is, hogy amikor megnyitódik, akkor user számára csak az legyen látható `bg-white sticky top-0 z-40`
