### ISSUE TITLE
Tag komponens közepes képernyőkön rossz

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#68]
720p és ahhoz közeli méreteken szétcsúszik a komponens.

![image](https://user-images.githubusercontent.com/61868789/134959996-0f5d9297-8425-403f-92cd-3e0accd0b693.png)

**Comment by perryd01** [comment]
*Tag / Member komponens
és
https://github.com/simonyiszk/mabe/pull/57#issuecomment-927176960

**Comment by perryd01** [comment]
önkényesen lezárom
