### ISSUE TITLE
Galéria - megnyitott album nézet

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#8]
- képek kitöltik a helyet
- ha rákattintunk megnyitja őket lapozó nézetben, mint a [spot.sch.bme.hu](spot.sch.bme.hu)-n

**Comment by perryd01** [comment]
@OmTheTurtle ezt simán kézzel összerakjuk vagy van rá valami tuti library?

**Comment by OmTheTurtle** [comment]
Szerintem sokkal jobban járunk azzal, ha keresünk egy lehető library-t, pl. react-image-gallery
