### ISSUE TITLE
Kezdőlap - direkt svg-k next image helyett

### ISSUE THREAD

**Issue by OmTheTurtle** [simonyiszk/mabe#94]
A next image lazy load-ot használ a képek betöltésére, de az a kezdőlapon nem néz ki jól az SVG-k esetében. Megoldás: komponensként deklarált SVG fájlok importálása / sima img tag használata.

**Comment by perryd01** [comment]
megoldás lehet?
[next image doc](https://nextjs.org/docs/api-reference/next/image#loading)
[megoldás source](https://stackoverflow.com/a/66639168)
