### ISSUE TITLE
Tagok page telefon bug

### ISSUE THREAD

**Issue by NoszDom** [simonyiszk/mabe#99]
A tagok oldalon ha mobilos Chromeról nyitod meg jobb oldalt van egy üres sáv _(hasonló mimt ami anno baloldalt volt Chromeban)_.
PC-n a reszponzív nézetben nekem nem volt gond amikor a PR-t néztem, csak mobilon.

![Screenshot_20211008_114518_com android chrome](https://user-images.githubusercontent.com/61868789/136535769-b661ac3e-0fa1-4b8a-b3cd-22272dca207e.jpg)

**Comment by OmTheTurtle** [comment]
Ahogy nézem ez azóta fixálva lett, valszeg amikor nézted még nem szinkronizálódott a fix hozzá.
